### ISSUE TITLE
QR code breaks transactions list

### ISSUE THREAD

**Issue by demcookies** [pauli2406/Garlicoin-Mobile-Wallet#4]
Getting wallet code trough scanning QR code will break 'last 25 transactions' list on the app. It will show some overflow code. 

..			
..			
..			
..			
..		//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js	
Bakery Gar..		navbar-collapse	
..		menu-text	
..		menu-text	
..		menu-text	
..		menu-text	
..		menu-text	
..			
..			
" + json.d..			
" + json.d..			
" + json.d..

**Comment by pauli2406** [comment]
I've only received this error if the address that was scanned is invalid. On my side scanning works fine.

To reproduce your issue I need more information. E.g. the  QR code you used
